### ISSUE TITLE
Preview of Taipy GUI pages

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-studio-gui#10]
**What would that feature address**

Visual Studio Code comes with a preview facility when edition Markdown files.
It would be great to allow for previewing Taipy visual elements embedded into Markdown code.

***Description of the ideal solution***

While working on a Markdown file, pressing `Ctrl-Shift-V` bring a new view in VSCode, showing a preview of Taipy visual elements that were defined.

***Caveats***

The quality of the rendering may greatly vary depending on the technologies used.

- Do we want real, live elements?
- Do we want image placeholders?

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented
